# Generated by Django 3.2.6 on 2021-10-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('nawes', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=700)),
                ('image', models.CharField(max_length=700)),
            ],
        ),
    ]
