# Generated by Django 3.2.6 on 2021-10-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookmarks',
            old_name='nawes',
            new_name='news',
        ),
    ]
