# Generated by Django 3.2.6 on 2021-12-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atricles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('votes', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('article', models.CharField(max_length=10000)),
            ],
        ),
    ]
