# Generated by Django 3.2.6 on 2022-02-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('votes', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('article', models.CharField(max_length=10000)),
                ('creator_email', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('article_id', models.IntegerField(default=0)),
                ('commented_date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=10000)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
