# Generated by Django 3.2 on 2022-01-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='creater_email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
