# Generated by Django 3.2.6 on 2022-01-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorarticles',
            name='creator_email',
            field=models.CharField(max_length=9223372036854775807),
        ),
    ]
