# Generated by Django 3.2.6 on 2021-12-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atricles',
            new_name='Articles',
        ),
    ]
