# Generated by Django 3.2.6 on 2022-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_email', models.CharField(max_length=100)),
                ('articleid', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='creater_email',
        ),
    ]
