# Generated by Django 3.2.6 on 2022-01-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_atricles_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('commented_date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=10000)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
