# Generated by Django 3.2.6 on 2022-01-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_creater_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='creater_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
