# Generated by Django 3.2.6 on 2022-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_authorarticles_creator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorarticles',
            name='creator_email',
            field=models.CharField(max_length=1000),
        ),
    ]
