# Generated by Django 3.2.6 on 2022-01-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article_id',
            field=models.IntegerField(default=0),
        ),
    ]
